version: '3.8'
services:
  # MySQL 数据库服务
  youguang-db:
    image: mysql:8.0
    container_name: youguang_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: youguang_db  # 自动创建数据库
      MYSQL_ROOT_PASSWORD: 123456    # 设置密码
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Redis 缓存服务
  youguang-redis:
    image: redis:latest
    container_name: youguang_redis
    ports:
      - "6379:6379"